/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signupformmain;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asif
 */
public class DatabaseFrame extends JFrame {

    /**
     * Creates new form DatabaseFrame
     */
    
    public DatabaseFrame(){
        initComponents();
        DefaultTableModel dbTable = (DefaultTableModel)databaseTable.getModel();
        
        /*Map<Integer, User> userMap = new HashMap<Integer, User>();
        try{
            BufferedReader bReader = new BufferedReader(new FileReader("database.txt"));
            String line;
            String info[];
            while((line = bReader.readLine())!=null){
                info = line.split(",");
                User data = new User(info[0],info[1],info[2],info[3]);
                userMap.put(1, data);
            }
        }catch(IOException e){
            e.printStackTrace();
        }*/
        
        /*HashSet<User> userSet = new HashSet<User>();
        
        try{
            BufferedReader buReader = new BufferedReader(new FileReader("database.txt"));
            String line;
            String info[];
            while((line = buReader.readLine())!=null){
                info = line.split(",");
                User data = new User(info[0],info[1],info[2],info[3]);
                userSet.add(data);
                dbTable.addRow(new Object[]{data.name,data.email,data.gender,data.dateOfBirth});
            }
            for(User u: userSet)
                    System.out.println(u.email);
            
            Iterator<User> itr = userSet.iterator();
            while(itr.hasNext()){
                System.out.println(itr.next().gender);
            }
        }catch(IOException e){
            e.printStackTrace();
        }*/
        
        ArrayList<User> userList = new ArrayList<User>(); // List Declaration
        
        User userObj = new User();         
        
        try {
            FileReader reader = new FileReader("database.txt");
            BufferedReader bufferedReader = new BufferedReader(reader);
 
            String line;
            String info[];
            while ((line = bufferedReader.readLine()) != null) {
                info = line.split(",");
                
                userObj.name = info[0];
                userObj.email = info[1];
                userObj.gender = info[2];
                userObj.dateOfBirth = info[3];
                
                userList.add(userObj); // Adding to list
                
                dbTable.addRow(new Object[]{userObj.name, userObj.email, userObj.gender, userObj.dateOfBirth}); // adding from list
                
                System.out.println(userObj.name); // Showing names in console.. same procedure for email, gender, dateOfBirth
            }
            reader.close();
            
                
 
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        databaseTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        databaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Gender", "Date of Birth"
            }
        ));
        jScrollPane1.setViewportView(databaseTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable databaseTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
