/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signupformmain;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asif
 */
public class DatabaseFrame extends JFrame {

    /**
     * Creates new form DatabaseFrame
     */
    
    public DatabaseFrame(){
        initComponents();
        DefaultTableModel dbTable = (DefaultTableModel)databaseTable.getModel();
        
        
        
        //ArrayList<String> arr = new ArrayList<String>();
        /*try {
            
            FileReader reader = new FileReader("database.txt");
            BufferedReader bufferedReader = new BufferedReader(reader); 
            String line;
            String info[];
            while ((line = bufferedReader.readLine()) != null) {
                //info = line.split(",");
                //arr.add(info[0]);
                //arr.add(info[1]);
                //arr.add(info[2]);
                //arr.add(info[3]);
                //dbTable.addRow(new Object[]{arr.get(0),arr.get(1),arr.get(2),arr.get(3)});
                dbTable.addRow(new Object[]{us.fn[0]});
                
            }
            reader.close();
 
        } catch (IOException e) {
            e.printStackTrace();
        }*/
        
        /*try {
            FileReader reader = new FileReader("database.txt");
            BufferedReader bufferedReader = new BufferedReader(reader);
 
            String line;
            String info[];
            while ((line = bufferedReader.readLine()) != null) {
                info = line.split(",");
                dbTable.addRow(new Object[]{info[0],info[1],info[2],info[3]});
            }
            reader.close();
 
        } catch (IOException e) {
            e.printStackTrace();
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        databaseTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        databaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Gender", "Date of Birth"
            }
        ));
        jScrollPane1.setViewportView(databaseTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable databaseTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
